"""test

Revision ID: 6382a8a76e18
Revises: ccf214ecac70
Create Date: 2023-05-04 03:02:15.552812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6382a8a76e18'
down_revision = 'ccf214ecac70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profiles', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'profiles', type_='unique')
    # ### end Alembic commands ###
