FROM python:3.11
WORKDIR /app_flask
COPY requirements.txt requirements.txt
RUN pip3 install --upgrade setuptools
RUN pip3 install -r requirements.txt
RUN chmod 755 .
COPY app ./app
COPY db ./db
COPY alembic.ini ./alembic.ini
COPY .env.prod ./.env.prod
CMD gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000у
