FROM python:3.11
WORKDIR /app_flask
COPY requirements.txt requirements.txt
RUN pip3 install --upgrade setuptools
RUN pip3 install -r requirements.txt
RUN chmod 755 .
COPY app ./app
COPY db ./db
COPY alembic.ini ./alembic.ini
COPY .env.prod ./.env.prod
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0"]
