version: '3.7'

services:
    postgres_db:
        image: postgres:14.5-alpine
        restart: on-failure
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    postgres_data: