version: '3.7'

services:
    postgres_db:
        image: postgres:14.5-alpine
        restart: on-failure
        env_file:
            - .env.prod
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    bot:
        build:
            dockerfile: Dockerfile_bot
        command: sh -c "make migrate && python3 -m bot"
        env_file:
            - .env.prod
        depends_on:
            - postgres_db
        volumes:
            - .:/bot
        restart: always
    app:
        build:
            dockerfile: Dockerfile_app
        env_file:
            - .env.prod
        depends_on:
            - postgres_db
            - bot
        restart: always

volumes:
    postgres_data: