name: Deploy

on:
  push:
    branches:
      - main

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install flake8

      - name: Run Flake8
        run: flake8 . --ignore=E402,F841,E302,E305,W503 --max-line-length=120 --statistics --show-source --extend-exclude=venv

  deployment:
    needs: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }} 
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.COMPOSE_PATH }}
            git pull
            sed -i "s/localhost:5432/postgres_db:5432/" alembic.ini
            sed -i "s/TG_BOT_KEY=set_key_here/TG_BOT_KEY=${{ secrets.TG_BOT_KEY }}/" .env.prod
            docker-compose pull
            docker-compose up -d
        continue-on-error: true

      - name: Rollback commit on error
        if: steps.deployment.outcome != 'success'
        run: git reset HEAD
